### ISSUE TITLE
Latest version does no more work on kodi 17 beta3 or 4

### ISSUE THREAD

**Issue by EricV** [pla1/plugin.image.500px#13] opened 2016-10-05 14:55 UTC
There is an API change that apparently rpevent the plugin to work. It starts, propose you categories, but as soon as you want to go somewhere where you can actually see a picture there is an API error message.

**Comment by snorrelo** [comment] 2016-10-06 20:19
Hi,
I just installed Kodi 17 beta3 and 500px 0.3.2 on my MacOS 10.12 here. I can't seem to reproduce the problem. Everything seems to work fine... Is it still failing for you or was a temporary error with the 500px api?

**Comment by EricV** [comment] 2016-10-06 21:18
Le 6 octobre 2016 22:19:42 GMT+02:00, "Snorre Løvås" notifications@github.com a écrit :

> Hi,
> I just installed Kodi 17 beta3 and 500px 0.3.2 on my MacOS 10.12 here.
> I can't seem to reproduce the problem. Everything seems to work fine...
> Is it still failing for you or was a temporary error with the 500px
> api?
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/pla1/plugin.image.500px/issues/13#issuecomment-252076722

## It is permanent. I tested with several git version that are between beta3 and beta4. I do not know exactly when it started to fails. I also notices that when starting kodi for the first time, it started to print a message about automatic plugin conversion about at the same time the plugin started to fail.

Eric Valette

**Comment by EricV** [comment] 2016-10-07 11:23
I tink that the bug is present already in beta3 on Linux.

**Comment by snorrelo** [comment] 2016-10-07 16:44
I updated to the latest nightly build, 17.0-BETA4 Git:20161007-b57c736, and I still see no problem here on MacOS. It might be a Linux regression or something that will hit other platforms later. Not sure how much can be done before we are closer to release and know more about the changes that will be introduced.

**Comment by EricV** [comment] 2016-10-07 18:42
[kodi.log.gz](https://github.com/pla1/plugin.image.500px/files/516890/kodi.log.gz)
Here is my log file. You will see the API error.

[kodi.log.gz](https://github.com/pla1/plugin.image.500px/files/516890/kodi.log.gz)

**Comment by snorrelo** [comment] 2016-10-07 20:00
Seems like the actual error you get is on line 1210,  'ERROR: 500px - Error from API: Failed to send request: [Errno 0] Error' which is a connect error for the 500px API. Often this is a certificate error because of some network interference/proxy, the program can't find the root certificates on the local machine or similar. 

We might be able to see what the error is if you enable component specific logging for libcurl in system settings, logging, enable component-specific logging, verbose logging for libcurl.
Restart Kodi and try to go into the plugin again until you get the error. The actual web-connections to api.500px.com will be logged and we might see the error there.

**Comment by EricV** [comment] 2016-10-07 20:04
On 07/10/2016 22:00, Snorre Løvås wrote:

> Seems like the actual error you get is on line 1210, 'ERROR: 500px -
> Error from API: Failed to send request: [Errno 0] Error' which is a
> connect error for the 500px API. Often this is a certificate error
> because of some network interference/proxy, the program can't find the
> root certificates on the local machine or similar.

I have no proxy, I'm via a direct connection and other devices with 
older version do work.

> We might be able to see what the error is if you enable component
> specific logging for libcurl in system settings, logging, enable
> component-specific logging, verbose logging for libcurl.
> Restart Kodi and try to go into the plugin again until you get the
> error. The actual web-connections to api.500px.com will be logged and we
> might see the error there.

The only specific thing I have is that I use openssl 1.1 on both failing 
linux machines

-- eric

**Comment by EricV** [comment] 2016-10-07 20:12
On 07/10/2016 22:00, Snorre Løvås wrote:

> We might be able to see what the error is if you enable component
> specific logging for libcurl in system settings, logging, enable
> component-specific logging, verbose logging for libcurl.
> Restart Kodi and try to go into the plugin again until you get the
> error. The actual web-connections to api.500px.com will be logged and we
> might see the error there.

I have no specific loging for libcurl I'm affraid (I see http DAv, 
ffmpeg, UpNP, ..).

**Comment by snorrelo** [comment] 2016-10-07 20:15
Mine says 'libcURL (http(s), dav)' so it might be the same as your 'http dav'

**Comment by EricV** [comment] 2016-10-07 20:26
[kodi.log.gz](https://github.com/pla1/plugin.image.500px/files/517062/kodi.log.gz)
Here is the file with the debug enable.
Notice that before the API error there are a lot of other errors.

[kodi.log.gz](https://github.com/pla1/plugin.image.500px/files/517062/kodi.log.gz)

**Comment by snorrelo** [comment] 2016-10-07 21:28
That didn't work. No more info was logged there, unfortunately. 

(The other warnings like

```
22:23:58 T:139799365150464 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.image.500px/?category=Journalism&feature=fresh_today&mode=feature&user_id=None
22:23:58 T:139799365150464   DEBUG: GetImageHash - unable to stat url plugin://plugin.image.500px/?category=Journalism&feature=fresh_today&mode=feature&user_id=None
```

is the system trying to get thumbnails it seems. But they aren't showstoppers here. I get them here too, but everything works as it should. It should probably be looked at, but aren't the reason it's failing for you)

I'm pretty sure it has to do with your certificate file and python not finding it, but not sure how to check. 

You might try to change:

```
            for count in xrange(self.api.retry_count):
                conn = httplib.HTTPSConnection(self.api.host) if self.api.secure else httplib.HTTPConnection(self.api.host)
```

starting on line 85 in plugin.image.500px/resources/lib/fivehundredpx/bind.py to

```
            for count in xrange(self.api.retry_count):
                import ssl 
                ssl._https_verify_certificates(enable=False)
                conn = httplib.HTTPSConnection(self.api.host) if self.api.secure else httplib.HTTPConnection(self.api.host)
```

to try to disable certificate checks, but it's a shot in the dark.

**Comment by EricV** [comment] 2016-10-08 08:06
On 07/10/2016 23:28, Snorre Løvås wrote:

> That didn't work. No more info was logged there, unfortunately.
> 
> (The other warnings like
> 
> |22:23:58 T:139799365150464 WARNING: CreateLoader - unsupported
> protocol(plugin) in
> plugin://plugin.image.500px/?category=Journalism&feature=fresh_today&mode=feature&user_id=None
> 22:23:58 T:139799365150464 DEBUG: GetImageHash - unable to stat url
> plugin://plugin.image.500px/?category=Journalism&feature=fresh_today&mode=feature&user_id=None
> |
> 
> is the system trying to get thumbnails it seems. But they aren't
> showstoppers here. I get them here too, but everything works as it
> should. It should probably be looked at, but aren't the reason it's
> failing for you)

Right. However, the url itself looks bad unless "plugin://" is 
specifically parsed by kodi (and transformed into file:// and a correct 
path and not curl or any classical url parsing library

> |for count in xrange(self.api.retry_count): conn =
> httplib.HTTPSConnection(self.api.host) if self.api.secure else
> httplib.HTTPConnection(self.api.host) |
> 
> starting on line 85 in
> plugin.image.500px/resources/lib/fivehundredpx/bind.py to
> 
> |for count in xrange(self.api.retry_count): import ssl
> ssl._https_verify_certificates(enable=False) conn =
> httplib.HTTPSConnection(self.api.host) if self.api.secure else
> httplib.HTTPConnection(self.api.host) |

Unfortunately no change:

10:40:39 T:140625483659008   ERROR: 500px - Error from API: Failed to send request: [Errno 0] Error

-- eric

**Comment by snorrelo** [comment] 2016-10-08 10:36
The plugin-namespace is handled by Kodi. But it should either be a folder or a playable item. Those entries are probably not set as a folder causing the warning.

Installed the kodi nightly on my Ubuntu 16.10 LTS and it worked fine. Installed openssl 1.1.1-dev from github and it started failing, though with a different error message. Might be the distro or openssl version or something completely different.  Since it wasn't the openssl made for the system it did not find the correct CA-files. 

Adding 
`export SSL_CERT_DIR=/etc/ssl/certs/`
to ~/.profile fixed the error for me, but it might not work on other distros.

So I'm pretty sure it is how your system handles SSL-requests and not the plugin in itself. I would try going back to the openssl that comes with your linux distribution and see if that works.

**Comment by EricV** [comment] 2016-10-08 12:22
Debian plans to move to openssl 1.1 anyway and this is the debian package, just the one that comes from experimental.  It install symbolic link for compatibilty reasons:

ls -l /usr/lib/ssl/certs
lrwxrwxrwx 1 root root 14 mars  18  2013 /usr/lib/ssl/certs -> /etc/ssl/certs

dpkg -s openssl
Package: openssl
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 1162
Maintainer: Debian OpenSSL Team pkg-openssl-devel@lists.alioth.debian.org
Architecture: amd64
Multi-Arch: foreign
Version: 1.1.0b-1
Depends: libc6 (>= 2.15), libssl1.1 (>= 1.1.0)
Suggests: ca-certificates
Conffiles:
 /etc/ssl/openssl.cnf f697ef5df0d006882e6326606e8dbf4a
Description: Secure Sockets Layer toolkit - cryptographic utility
 This package is part of the OpenSSL project's implementation of the SSL
 and TLS cryptographic protocols for secure communication over the
 Internet.
 .
 It contains the general-purpose command line binary /usr/bin/openssl,
 useful for cryptographic operations such as:
- creating RSA, DH, and DSA key parameters;
- creating X.509 certificates, CSRs, and CRLs;
- calculating message digests;
- encrypting and decrypting with ciphers;
- testing SSL/TLS clients and servers;
- handling S/MIME signed or encrypted mail.
  Homepage: https://www.openssl.org/

**Comment by pla1** [comment] 2017-06-05 12:08
This forum post help me on Ubuntu 16.04.2. https://forum.kodi.tv/showthread.php?tid=304613&pid=2553425#pid2553425

Closing issue.

**Closed as completed by pla1** 2017-06-05 12:08 UTC
